### ISSUE TITLE
AsciiArt looks ugly

### ISSUE THREAD

**Issue by scopolamin** [putterpanda/mimikittenz#3]
I get 
`â"?â"?â"?â-?â-?â-"â"?â"?â"?â"?â"?â"?â-"â-?â-Oâ"?â"?â"?â-"â-"â-"â-"â-"â-"â-"â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?
â"?â"?â"?â-Oâ-'â-'â-?â-"â-"â-"â-"â-?â-'â-'â-?â-"â-?â-?â-'â-^â-^â-'â-^â-^â-'â-?â-?â-"â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?
â"?â"?â-?â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-?â-"â"?â"?â"?â"?â"?â"?â"?â"?
â"?â"?â-Oâ-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-"â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-?â-"â"?â"?â"?â"?â"?â"?
â-?â-^â-'â-'â-^â-Oâ-'â-'â-^â-'â-'â-?â-^â-'â-'â-?â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-Oâ"?â"?â"?â"?â"?
â-?â-Oâ-'â-'â-'â-'â-'â-?â-'â-?â-'â-'â-'â-'â-'â-?â-?â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-?â"?â"?â"?â-"â-"
â-?â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-Oâ-"â-^â-'â-^
â-?â-'â-'â-'â-'mimikittenz-1.0-alphaâ-'â-'â-'â-'â-'â-'â-'â-'â-'â-?â-'â-^â-?â"?
â-?â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-?â-?â"?â"?â"?
â-?â-'â-'â-'â-'â-'â-'CAN I HAZ WAM?â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-Oâ"?â"?â"?â"?
â"?â-Oâ-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-?â"?â"?â"?â"?â"?
â"?â-?â-'â-'â-'jamieson@dringensec.comâ-'â-'â-'â-'â-Oâ"?â"?â"?â"?â"?
â"?â"?â-Oâ-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-?â"?â"?â"?â"?â"?â"?
â"?â"?â-?â-"â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-"â-Oâ"?â"?â"?â"?â"?â"?
â"?â"?â"?â"?â-?â-"â-"â-?â-?â-?â-?â-"â-"â-?â-?â-?â-?â-?â-?â-"â-"â-?â-?â-?â-?â-?â-?â-"â-"â-?â"?â"?â"?â"?â"?â"?â"?â"?`

Instead of

───▐▀▄──────▄▀▌───▄▄▄▄▄▄▄─────────────
───▌▒▒▀▄▄▄▄▀▒▒▐▄▀▀▒██▒██▒▀▀▄──────────
──▐▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▀▄────────
──▌▒▒▒▒▒▒▒▒▒▒▒▒▒▄▒▒▒▒▒▒▒▒▒▒▒▒▒▀▄──────
▀█▒▒█▌▒▒█▒▒▐█▒▒▀▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▌─────
▀▌▒▒▒▒▒▀▒▀▒▒▒▒▒▀▀▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▐───▄▄
▐▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▌▄█▒█
▐▒▒▒▒mimikittenz-1.0-alpha▒▒▒▒▒▒▒▒▒▐▒█▀─
▐▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▐▀───
▐▒▒▒▒▒▒CAN I HAZ WAM?▒▒▒▒▒▒▒▒▒▒▒▒▌────
─▌▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▐─────
─▐▒▒▒jamieson@dringensec.com▒▒▒▒▌─────
──▌▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▐──────
──▐▄▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▄▌──────
────▀▄▄▀▀▀▀▄▄▀▀▀▀▀▀▄▄▀▀▀▀▀▀▄▄▀────────

**Comment by wikijm** [comment]
Exact same issue with:
- Windows edition: Windows 10 Enterprise
- System type: 64-bit Operating System, x64-based processor
- OS langage: English (US)
- Execution way: Powershell console, Powershell ISE, PowerGUI

**Comment by scopolamin** [comment]
- Windows edition: Windows 7 Enterprise
- System type: 64-bit Operating System, x64-based processor
- OS language: English (US)
- Execution way: Powershell console

**Comment by tristandostaler** [comment]
Same. And the output that it gives looks like nothing.

**Comment by scopolamin** [comment]
`â"?â"?â"?â-?â-?â-"â"?â"?â"?â"?â"?â"?â-"â-?â-Oâ"?â"?â"?â-"â-"â-"â-"â-"â-"â-"â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?
â"?â"?â"?â-Oâ-'â-'â-?â-"â-"â-"â-"â-?â-'â-'â-?â-"â-?â-?â-'â-^â-^â-'â-^â-^â-'â-?â-?â-"â"?â"?â"?â"?â"?â"?â"?â"?â"?â"?
â"?â"?â-?â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-?â-"â"?â"?â"?â"?â"?â"?â"?â"?
â"?â"?â-Oâ-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-"â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-?â-"â"?â"?â"?â"?â"?â"?
â-?â-^â-'â-'â-^â-Oâ-'â-'â-^â-'â-'â-?â-^â-'â-'â-?â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-Oâ"?â"?â"?â"?â"?
â-?â-Oâ-'â-'â-'â-'â-'â-?â-'â-?â-'â-'â-'â-'â-'â-?â-?â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-?â"?â"?â"?â-"â-"
â-?â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-Oâ-"â-^â-'â-^
â-?â-'â-'â-'â-'mimikittenz-1.0-alphaâ-'â-'â-'â-'â-'â-'â-'â-'â-'â-?â-'â-^â-?â"?
â-?â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-?â-?â"?â"?â"?
â-?â-'â-'â-'â-'â-'â-'CAN I HAZ WAM?â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-Oâ"?â"?â"?â"?
â"?â-Oâ-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-?â"?â"?â"?â"?â"?
â"?â-?â-'â-'â-'jamieson@dringensec.comâ-'â-'â-'â-'â-Oâ"?â"?â"?â"?â"?
â"?â"?â-Oâ-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-?â"?â"?â"?â"?â"?â"?
â"?â"?â-?â-"â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-'â-"â-Oâ"?â"?â"?â"?â"?â"?
â"?â"?â"?â"?â-?â-"â-"â-?â-?â-?â-?â-"â-"â-?â-?â-?â-?â-?â-?â-"â-"â-?â-?â-?â-?â-?â-?â-"â-"â-?â"?â"?â"?â"?â"?â"?â"?â"?`

PatternName                                                 PatternMatch

---

MicrosoftOneDrive                                           login=obama%40hotmail.com&passwd=**TheRealPW**&type=11&PPFT=
CitrixNetScaler                                             login=obama%40hotmail.com&passwd=**TheRealPW**&type=11&PP...
Github                                                      %3D%3D&login=obama&password=**TheRealPW?♦???6♣ ☺   B   a...**

**Comment by orlyjamie** [comment]
Thanks guys, will look into this.

**Comment by orlyjamie** [comment]
#Issue fixed by using base64 encoded string and forcing output as UTF-8 rather than ANSI.
![fixed](https://cloud.githubusercontent.com/assets/6668807/16657670/a1081fa0-44a6-11e6-9b7c-4b40aa501316.png)
