### ISSUE TITLE
README is misleading

### ISSUE THREAD

**Issue by IISResetMe** [putterpanda/mimikittenz#7]
Please don't use the example:

`$matches=[mimikittenz.MemProcInspector]::InspectManyProcs("iexplore","chrome","firefox")`

`$matches` is an automatic variable (containing regex matches) in PowerShell

**Comment by orlyjamie** [comment]
Thanks Mathias  `Readme.md` corrected.

**Comment by IISResetMe** [comment]
Just saw it's in the function definition as well, sent PR
